Repository HiQoNetIntership2019/HiQoDataGeneratorClient, pull requests merged in 2019-07, with the labels that each got.

#3 Fix field types component
  src/Components/DropDown/DropDown.js
  src/Components/Table/FieldTypes/FieldTypesContainer.jsx
  src/store/table/fieldtypes/reducers.js
Labels: hotfix

#9 create constraints container
  package-lock.json
  src/Components/DropDown/DropDown.js
  src/Components/DropDown/style.css
  src/Components/Table/Constraints/ConstraintsContainer.jsx
  src/Components/Table/FieldTypes/FieldTypesContainer.jsx
  src/Components/Table/InputList/InputList.js
  src/Components/Table/InputList/ListEntry.js
  src/Components/Table/InputList/style.css
  src/Components/Table/TableRow/TableRow.js
  src/constants/ConstantsForAPI.js
  src/store/reducers.js
  src/store/table/constraints/actions.js
  src/store/table/constraints/reducers.js
Labels: enhancement

#12 added disabling functionality and input types
  src/Components/Table/Constraints/ConstraintsContainer.jsx
  src/Components/Table/InputList/InputList.js
  src/Components/Table/InputList/ListEntry.js
  src/Components/Table/InputList/ListEntryContainer.js
  src/Components/Table/InputList/SelectInput.js
  src/Components/Table/InputList/TextInput.js
  src/constants/ConstantsForAPI.js
  src/constants/ConstantsForConstraintTypes.js
  src/store/table/constraints/actions.js
  src/store/table/constraints/reducers.js
Labels: epic changes

#10 Added data generation
  package-lock.json
  package.json
  src/App.js
  src/Components/FileFormats/FileFormats.jsx
  src/Components/FileFormats/config.js
  src/Components/GenerationControl/GenerationControl.jsx
  src/Components/GenerationControl/GenerationControlContainer.jsx
  src/Components/GenerationControl/style.css
  src/Components/RadioButtonsGroup/RadioButtonsGroup.jsx
  src/Components/RadioButtonsGroup/style.css
  src/Components/Table/Table.js
  src/Components/Table/style.css
  src/constants/ConstantsForAPI.js
  src/core/download-file/index.js
  src/core/object-generation/index.js
  src/index.js
  src/store/file-formats/actions.js
  src/store/file-formats/reducers.js
  src/store/index.js
  src/store/reducers.js
Labels: magic? epic magic!!!

#11 Fix api url and props
  src/Components/Table/Datasets/DatasetsContainer.jsx
  src/store/table/datasets/actions.js
  src/store/table/datasets/reducers.js
Labels: bug police

#15 added absolute path imports
  src/App.js
  src/Components/FileFormats/FileFormats.jsx
  src/Components/GenerationControl/GenerationControl.jsx
  src/Components/GenerationControl/GenerationControlContainer.jsx
  src/Components/ObjectInfo/ObjectInfoContainer.jsx
  src/Components/RoundButton/RoundButton.js
  src/Components/Table/Constraints/ConstraintsContainer.jsx
  src/Components/Table/Datasets/CustomDatasetContainer/CustomDatasetContainer.js
  src/Components/Table/Datasets/DatasetsContainer.jsx
  src/Components/Table/FieldTypes/FieldTypesContainer.jsx
  src/Components/Table/InputList/InputList.js
  src/Components/Table/InputList/ListEntryContainer.js
  src/Components/Table/Table.js
  src/Components/Table/TableRow/TableRow.js
  src/constants/ConstantsForAPI.js
  src/store/reducers.js
  webpack.config.js
Labels: hotfix

#19 added regex-constraints exclusion logic
  src/Components/Table/InputList/ListEntryContainer.js
  src/constants/ConstantsForAPI.js
  src/core/object-generation/index.js
  src/store/table/constraints/actions.js
  src/store/table/constraints/constraintsHelpers.js
  src/store/table/constraints/reducers.js
Labels: enhancement

#20 Remove scripts from html
  package-lock.json
  package.json
  public/index.html
  src/index.js
  src/vendor.js
  webpack.config.js
Labels: bug police, enhancement

#18 Added generation fields in object
  package-lock.json
  public/index.html
  src/Components/GenerationControl/GenerationControl.jsx
  src/Components/GenerationControl/GenerationControlContainer.jsx
  src/Components/Table/Datasets/DatasetsContainer.jsx
  src/core/prototype-constructor/index.js
  src/core/sender-prototypes/index.js
Labels: epic changes, magic? epic magic!!!

#26 add validation for name
  package-lock.json
  src/Components/Table/TableRow/TableRow.js
  src/Components/Table/TableRow/style.css
Labels: magic? epic magic!!!
